from jet.llm.mlx.helpers.detect_repetition import clean_repeated_ngrams, find_repeated_consecutive_ngrams
from jet.logger import logger
from jet.transformers.formatters import format_json

text = "* !\n!r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\nShare\nShare"


result = find_repeated_consecutive_ngrams(text)
logger.success(format_json(result))

result = clean_repeated_ngrams(text)
logger.success(format_json(result))
