from jet.llm.mlx.helpers.detect_repetition import find_repeated_consecutive_ngrams
from jet.logger import logger
from jet.transformers.formatters import format_json

text = "# My top 20 favorite isekai animes not including the new isekai anime from 2025\n* ![](https://preview.redd.it/my-top-20-favorite-isekai-animes-not-including-the-new-v0-sll5rrrvgkee1.jpg?width=640&crop=smart&auto=webp&s=91601e195e3f70c3fc8eac69a42c4107e55af615)\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025](https://preview.redd.it/my-top-20-favorite-isekai-animes-not-including-the-new-v0-sll5rrrvgkee1.jpg?width=640&crop=smart&auto=webp&s=91601e195e3f70c3fc8eac69a42c4107e55af615)\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\n* ![]()\n![r/Isekai - My top 20 favorite isekai animes not including the new isekai anime from 2025]()\nShare\nShare"


result = find_repeated_consecutive_ngrams(text)
logger.success(format_json(result))
