from copy import deepcopy
from jet.adapters.langchain.chat_ollama import ChatOllama
from jet.logger import logger
from langchain_core.runnables import chain
from langchain_core.tools import BaseTool
from langchain_core.tools import InjectedToolArg, tool
from pydantic import BaseModel, Field
from typing import List
from typing import Optional, Type
from typing_extensions import Annotated
import ChatModelTabs from "@theme/ChatModelTabs";
import Compatibility from "@theme/Compatibility";
import Prerequisites from "@theme/Prerequisites";
import os
import shutil


OUTPUT_DIR = os.path.join(
    os.path.dirname(__file__), "generated", os.path.splitext(os.path.basename(__file__))[0])
shutil.rmtree(OUTPUT_DIR, ignore_errors=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)
log_file = os.path.join(OUTPUT_DIR, "main.log")
logger.basicConfig(filename=log_file)
logger.info(f"Logs: {log_file}")

PERSIST_DIR = f"{OUTPUT_DIR}/chroma"
os.makedirs(PERSIST_DIR, exist_ok=True)

"""
# How to pass run time values to tools


<Prerequisites titlesAndLinks={[
  ["Chat models", "/docs/concepts/chat_models"],
  ["LangChain Tools", "/docs/concepts/tools"],
  ["How to create tools", "/docs/how_to/custom_tools"],
  ["How to use a model to call tools", "/docs/how_to/tool_calling"],
]} />


<Compatibility packagesAndVersions={[
  ["langchain-core", "0.2.21"],
]} />

You may need to bind values to a [tool](/docs/concepts/tools/) that are only known at runtime. For example, the tool logic may require using the ID of the user who made the request.

Most of the time, such values should not be controlled by the LLM. In fact, allowing the LLM to control the user ID may lead to a security risk.

Instead, the LLM should only control the parameters of the tool that are meant to be controlled by the LLM, while other parameters (such as user ID) should be fixed by the application logic.

This how-to guide shows you how to prevent the model from generating certain tool arguments and injecting them in directly at runtime.

:::info Using with LangGraph

If you're using LangGraph, please refer to [this how-to guide](https://langchain-ai.github.io/langgraph/how-tos/pass-run-time-values-to-tools/)
which shows how to create an agent that keeps track of a given user's favorite pets.
:::

We can bind them to chat models as follows:


<ChatModelTabs
  customVarName="llm"
  overrideParams={{fireworks: {model: "accounts/fireworks/models/firefunction-v1", kwargs: "temperature=0"}}}
/>
"""
logger.info("# How to pass run time values to tools")

# from getpass import getpass


# if "OPENAI_API_KEY" not in os.environ:
#     os.environ["OPENAI_API_KEY"] = getpass()

llm = ChatOllama(model="llama3.2")

"""
## Hiding arguments from the model

We can use the InjectedToolArg annotation to mark certain parameters of our Tool, like `user_id` as being injected at runtime, meaning they shouldn't be generated by the model
"""
logger.info("## Hiding arguments from the model")



user_to_pets = {}


@tool(parse_docstring=True)
def update_favorite_pets(
    pets: List[str], user_id: Annotated[str, InjectedToolArg]
) -> None:
    """Add the list of favorite pets.

    Args:
        pets: List of favorite pets to set.
        user_id: User's ID.
    """
    user_to_pets[user_id] = pets


@tool(parse_docstring=True)
def delete_favorite_pets(user_id: Annotated[str, InjectedToolArg]) -> None:
    """Delete the list of favorite pets.

    Args:
        user_id: User's ID.
    """
    if user_id in user_to_pets:
        del user_to_pets[user_id]


@tool(parse_docstring=True)
def list_favorite_pets(user_id: Annotated[str, InjectedToolArg]) -> None:
    """List favorite pets if any.

    Args:
        user_id: User's ID.
    """
    return user_to_pets.get(user_id, [])

"""
If we look at the input schemas for these tools, we'll see that user_id is still listed:
"""
logger.info("If we look at the input schemas for these tools, we'll see that user_id is still listed:")

update_favorite_pets.get_input_schema().model_json_schema()

"""
But if we look at the tool call schema, which is what is passed to the model for tool-calling, user_id has been removed:
"""
logger.info("But if we look at the tool call schema, which is what is passed to the model for tool-calling, user_id has been removed:")

update_favorite_pets.tool_call_schema.model_json_schema()

"""
So when we invoke our tool, we need to pass in user_id:
"""
logger.info("So when we invoke our tool, we need to pass in user_id:")

user_id = "123"
update_favorite_pets.invoke({"pets": ["lizard", "dog"], "user_id": user_id})
logger.debug(user_to_pets)
logger.debug(list_favorite_pets.invoke({"user_id": user_id}))

"""
But when the model calls the tool, no user_id argument will be generated:
"""
logger.info("But when the model calls the tool, no user_id argument will be generated:")

tools = [
    update_favorite_pets,
    delete_favorite_pets,
    list_favorite_pets,
]
llm_with_tools = llm.bind_tools(tools)
ai_msg = llm_with_tools.invoke("my favorite animals are cats and parrots")
ai_msg.tool_calls

"""
## Injecting arguments at runtime

If we want to actually execute our tools using the model-generated tool call, we'll need to inject the user_id ourselves:
"""
logger.info("## Injecting arguments at runtime")




@chain
def inject_user_id(ai_msg):
    tool_calls = []
    for tool_call in ai_msg.tool_calls:
        tool_call_copy = deepcopy(tool_call)
        tool_call_copy["args"]["user_id"] = user_id
        tool_calls.append(tool_call_copy)
    return tool_calls


inject_user_id.invoke(ai_msg)

"""
And now we can chain together our model, injection code, and the actual tools to create a tool-executing chain:
"""
logger.info("And now we can chain together our model, injection code, and the actual tools to create a tool-executing chain:")

tool_map = {tool.name: tool for tool in tools}


@chain
def tool_router(tool_call):
    return tool_map[tool_call["name"]]


chain = llm_with_tools | inject_user_id | tool_router.map()
chain.invoke("my favorite animals are cats and parrots")

"""
Looking at the user_to_pets dict, we can see that it's been updated to include cats and parrots:
"""
logger.info("Looking at the user_to_pets dict, we can see that it's been updated to include cats and parrots:")

user_to_pets

"""
## Other ways of annotating args

Here are a few other ways of annotating our tool args:
"""
logger.info("## Other ways of annotating args")



class UpdateFavoritePetsSchema(BaseModel):
    """Update list of favorite pets"""

    pets: List[str] = Field(..., description="List of favorite pets to set.")
    user_id: Annotated[str, InjectedToolArg] = Field(..., description="User's ID.")


@tool(args_schema=UpdateFavoritePetsSchema)
def update_favorite_pets(pets, user_id):
    user_to_pets[user_id] = pets


update_favorite_pets.get_input_schema().model_json_schema()

update_favorite_pets.tool_call_schema.model_json_schema()



class UpdateFavoritePets(BaseTool):
    name: str = "update_favorite_pets"
    description: str = "Update list of favorite pets"
    args_schema: Optional[Type[BaseModel]] = UpdateFavoritePetsSchema

    def _run(self, pets, user_id):
        user_to_pets[user_id] = pets


UpdateFavoritePets().get_input_schema().model_json_schema()

UpdateFavoritePets().tool_call_schema.model_json_schema()

class UpdateFavoritePets2(BaseTool):
    name: str = "update_favorite_pets"
    description: str = "Update list of favorite pets"

    def _run(self, pets: List[str], user_id: Annotated[str, InjectedToolArg]) -> None:
        user_to_pets[user_id] = pets


UpdateFavoritePets2().get_input_schema().model_json_schema()

UpdateFavoritePets2().tool_call_schema.model_json_schema()

logger.info("\n\n[DONE]", bright=True)