from jet.logger import logger
from langchain_milvus import Milvus
import os
import shutil


OUTPUT_DIR = os.path.join(
    os.path.dirname(__file__), "generated", os.path.splitext(os.path.basename(__file__))[0])
shutil.rmtree(OUTPUT_DIR, ignore_errors=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)
log_file = os.path.join(OUTPUT_DIR, "main.log")
logger.basicConfig(filename=log_file)
logger.info(f"Logs: {log_file}")

PERSIST_DIR = f"{OUTPUT_DIR}/chroma"
os.makedirs(PERSIST_DIR, exist_ok=True)

"""
# Milvus

>[Milvus](https://milvus.io/docs/overview.md) is a database that stores, indexes, and manages
> massive embedding vectors generated by deep neural networks and other machine learning (ML) models.


## Installation and Setup

Install the Python SDK:
"""
logger.info("# Milvus")

pip install langchain-milvus

"""
## Vector Store

See a [usage example](/docs/integrations/vectorstores/milvus).

To import this vectorstore:
"""
logger.info("## Vector Store")


logger.info("\n\n[DONE]", bright=True)